spring:
  security:
    user:
      name: xxx
      password: xyz

  # http://www.h2database.com/html/features.html#auto_mixed_mode
  datasource:
    url: jdbc:h2:./db/startup;AUTO_SERVER=TRUE
    username: xxx
    password: xyz
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
